# Generated by Django 5.0.2 on 2024-03-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_adult_females_attendance_adult_males_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='submited_date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='total_offerings',
        ),
    ]
